apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: https://github.com/orgs/2023-4400-exp/packages/container/4421-go-server-ci/164944694?tag=80b3963e2c6fa6bebb295fc24bc67c354b64ed13
        name: go-server-ci
